# ####################################
# OS Image Manager
# ####################################


IMG_PREFIX	:= open-helper/1st
IMG_VER			:= latest


# ####################################
# Dashboard AREA
# ####################################
build:
	docker build -t $(IMG_PREFIX)/centos7:$(IMG_VER) centos7
